number1= int(input("enter fisrt number"))
number2= int(input("enter second number"))
number3= int(input("enter third number"))
number4= int(input("enter fourth number"))
number5= int(input("enter fifth number"))
number6= int(input("enter sixth number"))
number7= int(input("enter seventh number"))
number8= int(input("enter eighth number"))
number9= int(input("enter nineth number"))
number10= int(input("enter tenth number"))
print (number1 +  number2 + number3 + number4 + number5 + number6 + number7 + number8